#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# 1. Confirm system and user permissions.
printf "
=====================================================================
=                                                                   =
=                          Web Stack                                =
=                                                                   =
=  This script should never be used in a production environment.    =
=  Start uninstalling LAMP/LNMP (Linux, Apache/nginx, PHP, MariaDB).  =
=  QQ 309946202, E-mail xnfaganer@163.com                           =
=                                                                   =
=====================================================================
"
while true;do

  read -r -p "= Do you want to delete MySQL data generated by MariaDB when uninstalling? [Y/n]" confirm
  case $confirm in
      [yY][eE][sS]|[yY])
        yum remove http httpd-* nginx nginx-* php php-* MariaDB MariaDB-* -y
        find / -name mysql | xargs rm -rf
        echo "= LAMP/LNMP uninstall successfully."
        exit 0
      ;;

      [nN][oO]|[nN])
        yum remove http httpd-* nginx nginx-* php php-* MariaDB MariaDB-* -y
        echo "= LAMP/LNMP uninstall successfully."
        exit 0
      ;;

      *)
      echo "Invalid input."
      ;;
  esac

done